name: Deploy Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nodejs ${{ matrix.node }}
        uses: actions/setup-node@v1
      - name: Install dependencies
        env:
          CI: true
        run: npm install
      - name: Build the plugin
        run: npm run build:all
      - name: API Demo Deploy - https://kevinchappell.github.io/formBuilder/
        if: success()
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: demo/
          GH_PAT: ${{ secrets.GH_TOKEN }}
